# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b6de203f951a9abbd270d32297bca2f2beda114b39c92b6de64640600c3135470ba778c0325234fe08e84c35f012e235a113ff2ca2db6cffb1c565867f3c4a6

test:
  secret_key_base: ccb1b27881ef2d23557cd7edf62014fbf04ef08d69c9d44da0c6ca75bdfd2b8d5abe48d2bdcc1832369724d7735405af836f32ae33beb922ea7536423d93f743

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
